# -*- coding: utf-8 -*-
"""setup_windows.bat 汉化映射表：上游英文行 -> 中文行（自动提取自手写汉化版）"""

MAPPING = {
    'echo Coping is strong with this one...': 'echo Coping is strong with this one...',  # 梗，有意保留英文
    # ===== 网络超时增强（上游原版无超时，网络不通会卡死；汉化版加超时兜底）=====
    'for /f "usebackq tokens=*" %%A in (`powershell -Command "& { $rawUrl = \'https://raw.githubusercontent.com/optiscaler/OptiPatcher/main/OptiPatcher/dllmain.cpp\'; try { $code = (Invoke-WebRequest -Uri $rawUrl -UseBasicParsing).Content } catch { return \'ERR\' }; $supported = @(); $ueMatches = [Regex]::Matches($code, \'CHECK_UE\\s*\\(\\s*([a-zA-Z0-9_]+)\\s*\\)\'); foreach ($m in $ueMatches) { $base = $m.Groups[1].Value; $supported += ($base + \'-win64-shipping.exe\').ToLower(); $supported += ($base + \'-wingdk-shipping.exe\').ToLower(); }; $directMatches = [Regex]::Matches($code, \'exeName\\s*==\\s*[\\x22\\x27]([^\\x22\\x27]+)[\\x22\\x27]\'); foreach ($m in $directMatches) { $supported += $m.Groups[1].Value.ToLower(); }; $localFiles = Get-ChildItem *.exe | Select-Object -ExpandProperty Name; foreach ($file in $localFiles) { if ($supported -contains $file.ToLower()) { Write-Output \'YES\'; exit; } }; Write-Output \'NO\'; }"`) do (': 'for /f "usebackq tokens=*" %%A in (`powershell -Command "& { $rawUrl = \'https://raw.githubusercontent.com/optiscaler/OptiPatcher/main/OptiPatcher/dllmain.cpp\'; try { $code = (Invoke-WebRequest -Uri $rawUrl -UseBasicParsing -TimeoutSec 15).Content } catch { try { $code = (Invoke-WebRequest -Uri \'https://cdn.jsdelivr.net/gh/optiscaler/OptiPatcher@main/OptiPatcher/dllmain.cpp\' -UseBasicParsing -TimeoutSec 15).Content } catch { return \'ERR\' } }; $supported = @(); $ueMatches = [Regex]::Matches($code, \'CHECK_UE\\s*\\(\\s*([a-zA-Z0-9_]+)\\s*\\)\'); foreach ($m in $ueMatches) { $base = $m.Groups[1].Value; $supported += ($base + \'-win64-shipping.exe\').ToLower(); $supported += ($base + \'-wingdk-shipping.exe\').ToLower(); }; $directMatches = [Regex]::Matches($code, \'exeName\\s*==\\s*[\\x22\\x27]([^\\x22\\x27]+)[\\x22\\x27]\'); foreach ($m in $directMatches) { $supported += $m.Groups[1].Value.ToLower(); }; $localFiles = Get-ChildItem *.exe | Select-Object -ExpandProperty Name; foreach ($file in $localFiles) { if ($supported -contains $file.ToLower()) { Write-Output \'YES\'; exit; } }; Write-Output \'NO\'; }"`) do (',
    '        powershell -Command "Invoke-WebRequest -Uri \'https://github.com/optiscaler/OptiPatcher/releases/download/rolling/OptiPatcher.asi\' -OutFile \'OptiScaler\\plugins\\OptiPatcher.asi\'"': '        powershell -Command "$url=\'https://github.com/optiscaler/OptiPatcher/releases/download/rolling/OptiPatcher.asi\'; try { Invoke-WebRequest -Uri $url -OutFile \'OptiScaler\\plugins\\OptiPatcher.asi\' -TimeoutSec 60 } catch { try { Invoke-WebRequest -Uri (\'https://ghfast.top/\'+$url) -OutFile \'OptiScaler\\plugins\\OptiPatcher.asi\' -TimeoutSec 60 } catch { try { Invoke-WebRequest -Uri (\'https://gh-proxy.com/\'+$url) -OutFile \'OptiScaler\\plugins\\OptiPatcher.asi\' -TimeoutSec 60 } catch { try { Invoke-WebRequest -Uri (\'https://ghproxy.net/\'+$url) -OutFile \'OptiScaler\\plugins\\OptiPatcher.asi\' -TimeoutSec 60 } catch {} } } }',
    'ping -n 1 -w 3000 github.com >nul 2>&1': 'ping -n 1 -w 3000 github.com >nul 2>&1 || ping -n 1 -w 3000 ghfast.top >nul 2>&1',
    'echo v3.0-pre1': 'echo v3.0-pre1（汉化版）',
    '    echo Detected OptiScaler.sln or .git files^^!': '    echo 检测到 OptiScaler.sln 或 .git 文件！',
    '    echo If .sln or .git files are in the folder, congratz, you have the source code.': '    echo 如果文件夹里有 .sln 或 .git 文件，恭喜你，这是源码目录。',
    '\techo Now please try properly downloading OptiScaler.': '    echo 请从 GitHub Releases 页面下载正式安装包。',
    '\techo P.S. If you somehow have both the OptiScaler.dll and .sln file, then be nice, just delete the .sln file, re-run the BAT setup and hope for the best.': '    echo 补充：如果你同时有 OptiScaler.dll 和 .sln 文件，请删除 .sln 文件，重新运行本脚本。',
    '    echo Hint - use the Releases page on GitHub, or RTFM :^)': '    echo 提示 - 使用 GitHub Releases 页面，或阅读文档 :^)',
    '    echo It is recommended to delete them.': '    echo 建议删除。',
    '\techo.': '    echo.',
    '    echo OptiScaler "OptiScaler.dll" file is not found^^!': '    echo 未找到 OptiScaler "OptiScaler.dll" 文件！',
    '    echo Detected a folder permissions issue most likely. Might have more luck running the BAT as admin.': '    echo 很可能是文件夹权限问题，尝试以管理员身份运行本脚本。',
    '\techo OR': '    echo 或者',
    '    echo If "OptiScaler.dll" exists, please manually rename to a supported filename ^(e.g. dxgi/winmm.dll^) and you are done^^!': '    echo 如果 "OptiScaler.dll" 存在，请手动重命名为支持的文件名（如 dxgi/winmm.dll）即可完成！',
    '\techo No need to run the setup BAT again after renaming.': '    echo 重命名后无需再次运行安装脚本。',
    'REM Check if old pre-0.9 additional files exist, along with an existing Opti installation': 'REM 检查旧版 0.9 之前的残留文件，以及已存在的 Opti 安装',
    '    echo WARNING: Possible old OptiScaler file^(s^) detected^^!': '    echo 警告：检测到可能的旧版 OptiScaler 文件！',
    '    for %%F in (!OPTI_DLL_LIST!) do echo   - %%F ^(original filename: OptiScaler.dll^)': '    for %%F in (!OPTI_DLL_LIST!) do echo   - %%F （原始文件名：OptiScaler.dll）',
    '    echo These files may conflict with the current version of OptiScaler.': '    echo 这些文件可能与当前版本的 OptiScaler 冲突，建议删除。',
    '    echo Do you want to delete these files?': '    echo 是否删除这些文件？',
    '\techo [1] Yes': '\techo [1] 是',
    '    echo [2] No': '    echo [2] 否',
    '\tset /p "USER_CHOICE=Waiting - "': '\tset /p "USER_CHOICE=请选择 - "',
    '            echo Deleted nvapi64.dll': '            echo 已删除 nvapi64.dll',
    '            echo Deleted nvngx.dll': '            echo 已删除 nvngx.dll',
    '            echo Deleted OptiScaler.asi': '            echo 已删除 OptiScaler.asi',
    '            echo Deleted Remove OptiScaler.bat': '            echo 已删除 Remove OptiScaler.bat',
    '            echo Deleted Remove_OptiScaler.bat': '            echo 已删除 Remove_OptiScaler.bat',
    '            echo Deleted %%F': '            echo 已删除 %%F',
    '        echo Done^^!': '        echo 完成！',
    '        echo Skipping deletion. Note that these files may cause issues.': '        echo 已跳过删除。注意这些文件可能引起问题。',
    'REM Set paths based on current directory': 'REM 根据当前目录设置路径',
    'REM Check if the Engine folder exists': 'REM 检查是否存在 Engine 文件夹',
    '    echo Found Engine folder. If this is an Unreal Engine game, then please extract Optiscaler to #CODENAME#\\Binaries\\Win64': '    echo 检测到 Engine 文件夹。如果是虚幻引擎游戏，请将 OptiScaler 解压到 #CODENAME#\\Binaries\\Win64',
    '\techo Do not extract to the Engine folder^^!': '\techo 不要解压到 Engine 文件夹！',
    '\techo Example - \\Jedi Survivor\\SwGame\\Binaries\\Win64, \\Witchfire\\Witchfire\\Binaries\\Win64': '\techo 示例 - \\Jedi Survivor\\SwGame\\Binaries\\Win64, \\Witchfire\\Witchfire\\Binaries\\Win64',
    '    echo Continue installation to current folder?': '    echo 是否继续安装到当前文件夹？',
    '    echo [1] Yes': '    echo [1] 是',
    '\tset /p continueChoice="Waiting - "': '\tset /p continueChoice="请选择 - "',
    'REM Prompt user to select a filename for OptiScaler': 'REM 提示用户选择 OptiScaler 文件名',
    'echo Choose a filename for OptiScaler (default is dxgi.dll, most compatible):': 'echo 请为 OptiScaler 选择文件名（默认 dxgi.dll，兼容性最好）：',
    'echo (For Vulkan, use winmm.dll. For XGP/MS Store, winmm/version.dll may be better)': 'echo （Vulkan 游戏请用 winmm.dll；XGP/微软商店 winmm/version.dll 可能更好）',
    'set /p filenameChoice="Enter 1-8 (or press Enter for default): "': 'set /p filenameChoice="请输入 1-8（回车使用默认值）: "',
    '    echo Invalid choice. Please select a valid option.': '    echo 无效选项，请重新选择。',
    '    echo WARNING: %selectedFilename% already exists in the current folder.': '    echo 警告：%selectedFilename% 已存在于当前文件夹。',
    '\techo Do you want to overwrite %selectedFilename%?': '\techo 是否覆盖 %selectedFilename%？',
    '\tset /p overwriteChoice="Waiting - "': '\tset /p overwriteChoice="请选择 - "',
    "REM Wine doesn't support powershell": 'REM Wine 不支持 PowerShell',
    '    echo Using wine, skipping over spoofing checks.': '    echo 检测到 Wine，跳过伪装检查。',
    '    echo If you need, you can disable spoofing by setting Dxgi=false in the config': '    echo 如需关闭伪装，可在配置中设置 Dxgi=false',
    '    echo Nvidia driver files detected.': '    echo 检测到 N 卡驱动文件。',
    'REM Query user for GPU type': 'REM 询问用户 GPU 类型',
    'echo Are you using an Nvidia GPU or AMD/Intel GPU?': 'echo 你使用的是 N 卡还是 A 卡/Intel 核显？',
    'echo [1] AMD/Intel': 'echo [1] A 卡/Intel',
    'echo [2] Nvidia': 'echo [2] N 卡',
    '    set /p gpuChoice="Enter 1 or 2 (Detected Nvidia): "': '    set /p gpuChoice="请输入 1 或 2（检测到 N 卡）: "',
    '    set /p gpuChoice="Enter 1 or 2 (Detected AMD/Intel): "': '    set /p gpuChoice="请输入 1 或 2（检测到 A 卡/Intel）: "',
    'echo Invalid input. Please enter 1 or 2.': 'echo 无效输入，请输入 1 或 2。',
    'REM Skip spoofing if Nvidia': 'REM N 卡跳过伪装',
    'REM Query user for DLSS': 'REM 询问 DLSS 输入',
    'echo Will you try to use DLSS inputs to replace with FSR/XeSS? (enables Nvidia spoofing, required for DLSS-FG, Reflex-^>AL2)': 'echo 是否使用 DLSS 输入替换为 FSR/XeSS？（启用 N 卡伪装，DLSS-FG、Reflex-^>AL2 必需）',
    'echo If you want to change the setting later, edit OptiScaler.ini and set Dxgi=false to disable spoofing and reverse.': 'echo 如需更改，可编辑 OptiScaler.ini 设置 Dxgi=false 关闭伪装。',
    'echo [1] Yes': 'echo [1] 是',
    'echo [2] No': 'echo [2] 否',
    'set /p enablingSpoofing="Enter 1 or 2 (or press Enter for Yes): "': 'set /p enablingSpoofing="请输入 1 或 2（回车默认是）: "',
    '        echo Config file not found: %configFile%': '        echo 未找到配置文件：%configFile%',
    'REM Decide whether to run OptiPatcher': 'REM 决定是否运行 OptiPatcher',
    '    echo AMD/Intel GPU detected - running OptiPatcher check.': '    echo 检测到 A 卡/Intel，正在检查 OptiPatcher 兼容性。',
    '    echo OptiPatcher found: !foundOptiPatcher!': '    echo 发现 OptiPatcher：!foundOptiPatcher!',
    '    echo If the existing version works properly, might be best to keep it.': '    echo 如果现有版本工作正常，建议保留。',
    '\techo Do you want to re-download a possibly newer version?': '\techo 是否重新下载可能更新的版本？',
    '\tset /p optiRedownload="Waiting - "': '\tset /p optiRedownload="请选择 - "',
    '        echo Deleting !foundOptiPatcher!...': '        echo 正在删除 !foundOptiPatcher!...',
    '        echo Keeping existing OptiPatcher - skipping download.': '        echo 保留现有 OptiPatcher，跳过下载。',
    'REM Not installed - continue to download': 'REM 未安装，继续下载',
    'REM Check connectivity': 'REM 检查网络连接',
    'echo Checking for OptiPatcher compatibility...': 'echo 正在检查 OptiPatcher 兼容性...',
    'echo Press Ctrl+C if this gets stuck to skip to setup completion.': 'echo 网络不通时最多等待 15 秒后自动跳过。',
    '    echo Offline or GitHub blocked. Skipping OptiPatcher check.': '    echo 无法连接 GitHub 与 CDN 加速通道，跳过 OptiPatcher 检查。',
    '    echo OptiPatcher support detected^^!': '    echo 检测到 OptiPatcher 支持！',
    '    echo An Opti plugin used for unlocking DLSS/DLSS-FG inputs, avoiding spoofing and performance overhead in supported games.': '    echo 一个用于解锁 DLSS/DLSS-FG 输入的 Opti 插件，可避免伪装和性能开销。',
    '    echo More info available on OptiPatcher Github': '    echo 更多信息见 OptiPatcher GitHub',
    '\techo Download OptiPatcher.asi?': '\techo 下载 OptiPatcher.asi？',
    '\tset /p downloadOptiPatcher="Waiting - "': '\tset /p downloadOptiPatcher="请选择 - "',
    '        echo Preparing plugins folder...': '        echo 正在准备 plugins 文件夹...',
    '        echo Downloading OptiPatcher...': '        echo 正在下载 OptiPatcher...',
    '        echo Press Ctrl+C if this gets stuck to skip to setup completion.': '        echo 下载超时限制 60 秒，失败自动跳过。',
    '            echo OptiPatcher.asi downloaded successfully.': '            echo OptiPatcher.asi 下载成功。',
    '            echo Enabling ASI loading in OptiScaler.ini...': '            echo 正在启用 OptiScaler.ini 中的 ASI 加载...',
    '                echo Successfully enabled ASI loading in OptiScaler.ini^^!': '                echo 已在 OptiScaler.ini 中启用 ASI 加载！',
    '                echo Warning: OptiScaler.ini not found, could not enable LoadAsiPlugins.': '                echo 警告：未找到 OptiScaler.ini，无法启用 LoadAsiPlugins。',
    '            echo Failed to download OptiPatcher.asi.': '            echo OptiPatcher.asi 下载失败。',
    'REM Rename OptiScaler file': 'REM 重命名 OptiScaler 文件',
    '    echo Removing previous %selectedFilename%...': '    echo 正在删除旧 %selectedFilename%...',
    'echo Renaming OptiScaler file to %selectedFilename%...': 'echo 正在将 OptiScaler 文件重命名为 %selectedFilename%...',
    '    echo ERROR: Failed to rename OptiScaler file to %selectedFilename%. Most likely due to folder permissions issues.': '    echo 错误：重命名失败，很可能是文件夹权限问题。',
    '    echo Please rename OptiScaler.dll manually to %selectedFilename%^^! No need to run setup BAT again after that.': '    echo 请手动将 OptiScaler.dll 重命名为 %selectedFilename%！之后无需再次运行脚本。',
    'echo  OptiScaler setup completed successfully...': 'echo  OptiScaler 安装成功！',
    'echo echo v2.8 - now with OptiPatcher support': 'echo echo v3.0-pre1（汉化版）',
    'echo REM Check if OptiScaler installation exists': 'echo echo REM 检查 OptiScaler 是否已安装',
    'echo     echo Existing OptiScaler installation detected^^^^!': 'echo     echo 检测到已安装的 OptiScaler！',
    'echo     for %%%%F in ^(!OPTI_DLL_LIST!^) do echo   - %%%%F - original filename: OptiScaler.dll': 'echo     for %%%%F in ^(!OPTI_DLL_LIST!^) do echo   - %%%%F - 原始文件名：OptiScaler.dll',
    'echo echo Do you want to remove OptiScaler?': 'echo echo 是否卸载 OptiScaler？',
    'echo echo [1] Yes': 'echo echo [1] 是',
    'echo echo [2] No': 'echo echo [2] 否',
    'echo set /p removeChoice="Waiting - "': 'echo set /p removeChoice="请选择 - "',
    'echo     echo Deleting OptiPatcher if present': 'echo     echo 删除 OptiPatcher（如果存在）',
    'echo     echo OptiScaler removed^^^^! Ignore the warnings about missing files.': 'echo     echo OptiScaler 已卸载！忽略关于缺失文件的警告。',
    'echo     echo Operation cancelled.': 'echo     echo 操作已取消。',
    'echo Uninstaller created.': 'echo 卸载脚本已生成。',
}

# 汉化版额外插入的内容（锚点行 -> 插入的额外行）
EXTRA = {
    'del "!! README_EXTRACT ALL FILES TO GAME FOLDER !!.txt" 2>nul': [
        'echo.',
        'echo ============================================',
        'echo   OptiScaler 中文汉化版安装向导',
        'echo   汉化版与上游完全兼容，开箱即用',
        'echo ============================================',
        'echo.',
        'del "!! EXTRACT ALL FILES TO GAME FOLDER !!" 2>nul',
    ],
    'echo          _/      /    ': [
        'echo.',
        'echo 按 Insert 可在游戏内打开 OptiScaler 菜单',
        'echo.',
    ],
}

# 文件开头额外插入的注释块
HEADER = [
    'REM ============================================================',
    'REM OptiScaler 中文汉化版安装向导（CHS）',
    'REM 基于上游 setup_windows.bat 汉化，逻辑与上游完全一致',
    'REM 注意：本文件必须以 GBK/ANSI 编码保存，否则中文会乱码！',
    'REM ============================================================',
]
